allowBuilds:
  '@swc/core': true
  bufferutil: false
  core-js: false
  esbuild: true
  utf-8-validate: false
minimumReleaseAgeExclude:
  - '@clerk/localizations@4.13.6'
  - '@clerk/shared@4.25.6'
  - '@clerk/ui@1.25.6'
